### ISSUE TITLE
Resources for all platforms

### ISSUE THREAD

**Issue by jdnichollsc** [TeamMaestro/angular-native-seed#65]
Hi guys,
One question, where is the best place to have the same resources (images) between iOS, Android and Web? Exist any option to do that?
Thanks in advance, Nicholls

**Comment by sean-perkins** [comment]
Place the image (and shared assets) in `src/assets`. Part of the symlink script copies this into `nativescript/src/assets` so that the {N} app has access to the same contents. 

https://github.com/TeamMaestro/angular-native-seed/blob/master/symlink.js#L17

**Comment by jdnichollsc** [comment]
Yes, but how can you access to these resources using the *icon* property? For example icon="res://menu"? I'm testing with *ActionItems*

**Comment by sean-perkins** [comment]
I'm pretty sure that `res://` references from the specific platforms `App_Resources` folder. Android is a bit of a pain, because of all the sub folders & I'm not actually sure which folder represents which device type. 

You have a few options to handle this.

1. Adjust the `symlink.js` script to link `./src/assets/images` to `./nativescript/App_Resources/iOS` as well as all the miscellaneous Android folders (unless theres a main folder that applies to all of them). 
2. Add a new script inside `nativescript/gulpfile.js` that copies images out of `nativescript/src/assets` and places them into the correct `App_Resources` folder as mentioned above. 

That script may look like:

```
gulp.task('project.Images', () => {
    return gulp.src([`${SRC}assets/*.png`, `${SRC}assets/*.jpg`, `${SRC}assets/*.gif`], { follow: true })
        .pipe(gulp.dest('App_Resources/iOS'))
        .pipe(gulp.dest('App_Resources/Android'));
});
```

then as part of this:
```
gulp.task(
    'build.Default',
    gulp.series(
        'clean.Dist',
        'resources.App_Resources',
        'resources.Assets',
        'project.Typescript',
        'project.Styles',
        'tns.Templates',
        'tns.Styles',
        'tns.Typescript'
    )
);
```

add `project.Images` to the `series` function after `project.Styles`.

**Comment by jdnichollsc** [comment]
@sean-perkins yeah, you'right. With Android is more difficult because each *drawable* folder represents the *Display pixel density (ldpi/mdpi/hdpi/xhdpi/nodpi/tvdpi)*. I think manually is the best option for now 👍 
Thanks for all my friend!

**Comment by triniwiz** [comment]
if you don't want to create multiple drawables you can create a new folder in the `App_Resources/android` new it drawable then drop your file there

**Comment by jdnichollsc** [comment]
@triniwiz you're right my friend, that folder is for the default resources 🍻
